# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  system.debug: false
  sqlDwSolutionName: 'ddo_azuresqldw_dw'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'bin/Debug/sqldwproject.dacpac'
    ArtifactName: 'sql_dw_dacpac'
  displayName: 'Publish SQL DACPAC'